### ISSUE TITLE
在非mybatis环境的项目中启动必现异常

### ISSUE THREAD

**Issue by radcat1987** [kana112233/mybatis-plus-plugin#7]
非mybatis环境下项目，启动时发现

java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.baomidou.plugin.idea.mybatisx.inspection.PlusEntityPropInspection.getVirtualFile(PlusEntityPropInspection.java:42)
	at com.baomidou.plugin.idea.mybatisx.inspection.PlusEntityPropInspection.getVirtualFile(PlusEntityPropInspection.java:37)
	at com.baomidou.plugin.idea.mybatisx.inspection.PlusEntityPropInspection.getVirtualFile(PlusEntityPropInspection.java:37)
	at com.baomidou.plugin.idea.mybatisx.inspection.PlusEntityPropInspection.getVirtualFile(PlusEntityPropInspection.java:37)
	at com.baomidou.plugin.idea.mybatisx.inspection.PlusEntityPropInspection.getVirtualFile(PlusEntityPropInspection.java:37)
	at com.baomidou.plugin.idea.mybatisx.inspection.PlusEntityPropInspection.getVirtualFile(PlusEntityPropInspection.java:37)
	at com.baomidou.plugin.idea.mybatisx.inspection.PlusEntityPropInspection.getVirtualFile(PlusEntityPropInspection.java:37)
	at com.baomidou.plugin.idea.mybatisx.inspection.PlusEntityPropInspection.getVirtualFile(PlusEntityPropInspection.java:37)
	at com.baomidou.plugin.idea.mybatisx.inspection.PlusEntityPropInspection.getCustomComponents(PlusEntityPropInspection.java:83)
	at com.intellij.spring.contexts.model.AbstractSimpleLocalModel.computeCustomBeans(AbstractSimpleLocalModel.java:56)
	at com.intellij.spring.contexts.model.AbstractSimpleLocalModel.access$000(AbstractSimpleLocalModel.java:27)
	at com.intellij.spring.contexts.model.AbstractSimpleLocalModel$1$1.compute(AbstractSimpleLocalModel.java:39)
	at com.intellij.spring.contexts.model.AbstractSimpleLocalModel$1$1.compute(AbstractSimpleLocalModel.java:35)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:38)
	at com.intellij.spring.contexts.model.BeansSpringModel.calculateLocalBeans(BeansSpringModel.java:63)
	at com.intellij.spring.contexts.model.CachedLocalModel.getLocalBeans(CachedLocalModel.java:28)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel.processLocalBeans(AbstractSimpleSpringModel.java:101)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel.access$100(AbstractSimpleSpringModel.java:24)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel$1.doProcessBeans(AbstractSimpleSpringModel.java:31)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel$1.doProcessBeans(AbstractSimpleSpringModel.java:27)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel$LocalBeansCachingProcessor.findPointers(AbstractSimpleSpringModel.java:59)
	at com.intellij.spring.contexts.model.SpringCachingProcessor$1.createValue(SpringCachingProcessor.java:46)
	at com.intellij.spring.contexts.model.SpringCachingProcessor$1.createValue(SpringCachingProcessor.java:42)
	at com.intellij.spring.contexts.model.SpringCachingProcessor$SpringSLRUCache.get(SpringCachingProcessor.java:107)
	at com.intellij.spring.contexts.model.SpringCachingProcessor.process(SpringCachingProcessor.java:73)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel.processLocalBeansByClass(AbstractSimpleSpringModel.java:137)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel.processByClass(AbstractSimpleSpringModel.java:92)
	at com.intellij.spring.contexts.model.AbstractProcessableModel.lambda$processByClass$0(AbstractProcessableModel.java:26)
	at com.intellij.spring.contexts.model.visitors.CommonSpringModelVisitorContext.visit(CommonSpringModelVisitorContext.java:30)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:50)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:59)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:51)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:59)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:51)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:59)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:51)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelatedModels(SpringModelVisitors.java:30)
	at com.intellij.spring.contexts.model.AbstractProcessableModel.processByClass(AbstractProcessableModel.java:26)
	at com.intellij.spring.model.utils.SpringModelSearchers.containsBean(SpringModelSearchers.java:96)
	at com.intellij.spring.model.utils.SpringModelSearchers.doesBeanExist(SpringModelSearchers.java:84)
	at com.intellij.spring.java.SpringJavaClassInfo.lambda$new$0(SpringJavaClassInfo.java:78)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.spring.java.SpringJavaClassInfo.isMapped(SpringJavaClassInfo.java:232)
	at com.intellij.spring.java.SpringJavaClassInfo.getMappedDomBeans(SpringJavaClassInfo.java:241)
	at com.intellij.spring.java.SpringJavaClassInfo.lambda$new$2(SpringJavaClassInfo.java:91)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.spring.java.SpringJavaClassInfo.getMappedProperties(SpringJavaClassInfo.java:288)
	at com.intellij.spring.java.SpringJavaClassInfo.isMappedProperty(SpringJavaClassInfo.java:315)
	at com.intellij.spring.code.SpringImplicitUsageProvider.isBeanSetterOrLifeCycleMethod(SpringImplicitUsageProvider.java:123)
	at com.intellij.spring.code.SpringImplicitUsageProvider.isImplicitUsage(SpringImplicitUsageProvider.java:48)
	at com.intellij.codeInspection.reference.RefUtil.isImplicitUsage(RefUtil.java:26)
	at com.intellij.codeInspection.deadCode.UnusedDeclarationInspectionBase.isEntryPoint(UnusedDeclarationInspectionBase.java:351)
	at com.intellij.codeInspection.deadCode.UnusedDeclarationInspectionBase.isDeclaredAsEntryPoint(UnusedDeclarationInspectionBase.java:376)
	at com.intellij.codeInspection.unusedReturnValue.UnusedReturnValueLocalInspection.checkMethod(UnusedReturnValueLocalInspection.java:58)
	at com.intellij.codeInspection.AbstractBaseJavaLocalInspectionTool$1.visitMethod(AbstractBaseJavaLocalInspectionTool.java:55)
	at com.intellij.psi.impl.source.PsiMethodImpl.accept(PsiMethodImpl.java:273)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$8(LocalInspectionsPass.java:321)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:169)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:111)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$9(LocalInspectionsPass.java:320)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1101)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpCC(ForkJoinPool.java:1115)
	at java.base/java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:1687)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1039)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:58)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:58)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitRestElementsAndCleanup(LocalInspectionsPass.java:333)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect(LocalInspectionsPass.java:203)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:119)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

**Comment by radcat1987** [comment]
![image](https://user-images.githubusercontent.com/1320466/65028716-0d585200-d96f-11e9-8112-2f11de5c03c6.png)

**Comment by kana112233** [comment]
已经修改
